config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {:registraions => "users/registrations"}
                     
  root 'static_pages#index'

  get '5k_race' => 'static_pages#race_5k', :as => "race_5k"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 validates_uniqueness_of :email
 validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
 validates :name, presence: true
 validates :age, presence: true, numericality: {greater_than: 0}
 validates :phone, presence: true

 # def age(dob)
 #  now = Time.now.utc.to_date
 #  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
 # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :phone, :age, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :phone, :age, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end

  def race_5k
    
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
#before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
# before_filter :configure_permitted_parameters
#   # GET /resource/sign_up
#   def new
#     super
#     User.new(user_params)
#   end
#
#   # POST /resource
#   def create
#     super
#     User.create(user_params)
#   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  #
  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :phone, :age) }
  # end
  #
  # private
  #
  # def user_params
  #   params.require(:user).permit(:name, :age, :phone)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">
      <span class="glyphicon glyphicon-remove"></span></a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homeless Cycles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Custom CSS -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <%= csrf_meta_tags %>

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to 'Homeless Cycles', root_path, :class => 'navbar-brand' %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to 'About', root_path + "#about", :class => 'navbar-link' %>
                  </li>

                  <!-- Only show 5k Race button if logged in -->
                  <%- if user_signed_in? %>
                    <li>
                      <%= link_to '5K Race', race_5k_path, :class => 'navbar-link' %>
                    </li>
                  <% end %>
              </ul>
              <ul class="nav navbar-nav navbar-right">
              <!-- Handles Devise Login -->
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'  %>
                </li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
              <% else %>
               <li>
                 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
               </li>
                <li>
                  <%= link_to 'Login', "#loginModal", :remote => true, 'data-toggle' => "modal", 'data-target' => "#loginModal"%>
                </li>
              <% end %>
                </ul>
              <!-- *************************** -->
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  <!-- Yield will render different views depending on the route -->
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
<footer class="footer navbar-fixed-bottom" style="background-color:white; padding-top:10px;">
     <div class="container">
       <p class="text-muted" style="text-align:center">
       Copyright ©2015 Charleston Souther University All rights reserved.
     </p>
     </div>
</footer>

<%= render "static_pages/login_modal" %>
</html>

app/views/static_pages/_login_modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
         <div id="contentdiv" class="contcustom">
            <span class="fa fa-spinner bigicon"></span>
             <h2>Login</h2>
             <div>
                 <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: { id: "login-modal-form" })do |f| %>
                   <%= f.error_notification %>
                   <%= f.email_field :email, :id => "username", :placeholder => "username", :onkeypress => "check_values();" %>
                   <%= f.password_field :password, :id => "password", :placeholder => "password", :onkeypress => "check_values();"%>
                   <%= button_tag(id: "button1", type: 'submit', class: "btn btn-default wide hidden") do %>
                      <span class="fa fa-check med"></span>
                   <% end %>
                   <span id="lock1" class="fa fa-lock medhidden redborder"></span>

                     <!-- Remeber me button -->
                     <%- if devise_mapping.rememberable? %>
                      <div class="checkbox">
                        <label>
                          <%= f.check_box :remember_me, :style=> "width:auto", :inline_label => true %>Remember me
                        </label>
                      </div>
                    <% end -%>

                <% end %>
                <br>
                <div class="btn-group" role="group" style="width:100%; display:flex">
                <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                  <%= link_to "Sign up", new_registration_path(resource_name), :class => "btn btn-default btn-sm redborder", :style => "width:50%"%><br />
                <% end -%>

                <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                  <%= link_to "Forgot password?", new_password_path(resource_name), :class => "btn btn-default btn-sm redborder", :style => "width:50%" %><br />
                <% end -%>
               </div>
             </div>
         </div>
       </div>
    </div>
  </div>
</div>
</div>


<script>
//--Login Modal Checks that something has been entered into the username and password fields
function check_values() {
  if ($("#username").val().length != 0 && $("#password").val().length != 0) {
      $("#button1").removeClass("hidden").animate({ left: '250px' });
      $("#lock1").addClass("hidden").animate({ left: '250px' });
  }
};
</script>

app/views/static_pages/index.html.erb
<!-- This is the center image/logo on homepage -->
<header class="image-bg-fluid-height">
    <%= image_tag("logo.png", :class=>"img-responsive img-center") %>
</header>

<!-- Content Section -->
<section>
    <div class="container">
        <div class="row">
            <div id="about" class="col-lg-12" style="height:500px;">
                <h1 class="section-heading">Bicycles for the Homeless</h1>
                <p class="lead section-lead">Here at Homeless Cycles our number one priority is the redistribution of bicycles to those of the community that need them the most.</p>
                <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, suscipit, rerum quos facilis repellat architecto commodi officia atque nemo facere eum non illo voluptatem quae delectus odit vel itaque amet.</p>
            </div>
        </div>
    </div>
</section>

app/views/static_pages/race_5k.html.erb
<div class="image-bg-fixed-height ">
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                    <fieldset>
                        <legend class="text-center header">5K Race Details</legend>
                        <div style="font-size:16px;">

                        <p>
                          Come join us in a fun run to raise money for bikes for our program to provide transportation to those in need and to bring happiness to children that do not have the means for a bike.  You can give a donation as an entrance fee at the event or you can contact our coordinator, John, at 862-453-8920; who will get you on a sponsor sheet where we already have commitments from local businesses per runner.
                        </p>
                        <p>

                         The run will take place on January 7, 2016.  By logging in you will be registered for the race and can access the route map.  We will gather at the starting point A at 8 am and the race will start at 8:40.  This is a 5K run and we will have volunteers at water stations along the route. The local Fire and Rescue unit has volunteered to help in case of a medical emergency, but this is just a FUN run and no need to hurt ourselves.
                        </p>
                        <p>
                          Come on out and meet your neighbors while supporting community unity.  Bring the family. See you there.
                        </p>
                      </div>
                    </fieldset>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <div class="panel panel-default">
                    <div class="text-center header">Where Is The Race?</div>
                    <div class="panel-body text-center">
                        <div>
                        Wannamaker Park <br/>
                        8888 University Blvd,
                        <br />
                        North Charleston, SC 29406<br />
                        service@company.com<br />
                        </div>
                        <hr />
                          <div id="map-canvas" style="min-height:300px;"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Google Maps Javascript API -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHRoCyncUb07_TziarFs9ekM1eGqkOQ8M">
</script>

<!-- Page specific functions to build race map -->
<script type="text/javascript">
  var start = {lat: 32.977113, lng: -80.055752}; //"8888 University Blvd, North Charleston, SC 29406";
  var finish = {lat: 32.982704, lng: -80.071450}; //"9200 University Blvd, North Charleston, SC 29406";

  //-- Called when document is ready
  function initMap()
  {
    var directionsService = new google.maps.DirectionsService;
    var directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers : true});
    var map = new google.maps.Map(document.getElementById('map-canvas'), {
      zoom: 7,
      center: start
    });
    directionsDisplay.setMap(map);
    calculateAndDisplayRoute(directionsService, directionsDisplay);

    // --Create Custom Markers for start and finish points
    var icon = "https://chart.googleapis.com/chart?chst=d_map_spin&chld=.85|0|33cc33|9|b|Start";
    var marker = new google.maps.Marker({
      title: "Start",
      icon: icon,
      position: start,
      map: map

    });

    var icon2 = "https://chart.googleapis.com/chart?chst=d_map_spin&chld=.85|0|ff0000|9|b|Finish";
    var marker = new google.maps.Marker({
      title: "Finish",
      icon: icon2,
      position: finish,
      map: map

    });
  }

  function calculateAndDisplayRoute(directionsService, directionsDisplay)
  {
    directionsService.route({
      origin: start,
      destination: finish,
      travelMode: google.maps.TravelMode.WALKING
    }, function(response, status) {
      if (status === google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);


      } else {
        window.alert('Directions request failed due to ' + status);
      }
    });
    }

    $(document).ready(function(){
      initMap();
    })
</script>

<style>
    .header {
        background-color: #F5F5F5;
        color: #4d4d4d;
        height: 70px;
        font-size: 27px;
        padding: 10px;
    }
</style>